os:
- linux
- osx
- windows
dist: xenial
language: node_js
node_js:
- node
- 12 # EOL Apr 22
- 10 # EOL Apr 21
cache:
  yarn: true
matrix:
  fast_finish: true
env:
  global:
    - YARN_GPG=no # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
before_script: yarn bootstrap
script: yarn test
after_success:
- test ${TRAVIS_JOB_NUMBER#*.} == 1 && test ${TRAVIS_OS_NAME} == "linux" && travis_retry yarn global add codeclimate-test-reporter
- test ${TRAVIS_JOB_NUMBER#*.} == 1 && test ${TRAVIS_OS_NAME} == "linux" && codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 7a4b78747587abb295ccb41439d7d067b9de2d885a766e7e88d5e8409599d2ea
